### PR TITLE
Comment Netlify Deploy URL

### PR DESCRIPTION
**Pull request by nwtgck**
I'll use force push to confirm.

### CODE REVIEW

**Comment by peaceiris** [comment]
あとは jq で取って outputs として github-script に渡す感じで。

**Comment by nwtgck** [comment]
@peaceiris  Thanks! I'll use `require('fs')`. Cannot`fs` access to the local file?

**Comment by nwtgck** [comment]
`fs` can be used!

**Comment by peaceiris** [comment]
```yaml
- name: Set URL
  id: deploy_url
  run: |
    export URL=$(cat ./json.json | jq -r '.deploy_url')
```

**Comment by nwtgck** [comment]
@peaceiris Great! But, I'd like to avoid environment variables as possible.

**Comment by peaceiris** [comment]
Good!

**Pull request merged**
